
api_keys:
  openai: "PASTE_YOUR_OPENAI_API_KEY_HERE"
  anthropic: "PASTE_YOUR_ANTHROPIC_API_KEY_HERE"
  deepseek: "PASTE_YOUR_DEEPSEEK_API_KEY_HERE"

api_endpoints:
  openai: "https://api.openai.com/v1/chat/completions"
  anthropic: "https://api.anthropic.com/v1/messages"
  deepseek: "https://api.deepseek.com/chat/completions"

model_names:
  chatgpt: "gpt-4-turbo"
  claude: "claude-4-sonnet-20240229" 
  deepseek: "deepseek-v3-chat"
